# Generated by Django 5.1.7 on 2025-03-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_secret_destruction_animation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
