# Generated by Django 5.1.7 on 2025-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_last_login_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='destruction_animation',
            field=models.CharField(choices=[('none', 'No Animation'), ('fire', 'Fire'), ('explode', 'Explode'), ('shred', 'Shred')], default='none', max_length=20),
        ),
    ]
